# Generated by Django 4.2.7 on 2023-11-20 12:55

import FlowerLensBackendComponent.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlowerLensBackendComponent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='image_folder_path',
        ),
        migrations.CreateModel(
            name='FlowerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=FlowerLensBackendComponent.models.flower_image_directory_path)),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlowerLensBackendComponent.flower')),
            ],
        ),
    ]
