# Generated by Django 4.2.7 on 2023-12-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlowerLensBackendComponent', '0004_aimodel_metricstable_matriximage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='file_path',
        ),
    ]
