# Generated by Django 4.2.7 on 2023-12-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowerLensBackendComponent', '0005_remove_aimodel_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('heatmap', models.ImageField(upload_to='heatmaps/')),
            ],
        ),
    ]
