# Generated by Django 4.2.7 on 2023-12-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowerLensBackendComponent', '0006_predictionresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresult',
            name='confidence',
            field=models.CharField(max_length=255),
        ),
    ]
