# Generated by Django 4.2.7 on 2023-12-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlowerLensBackendComponent', '0008_alter_predictionresult_heatmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='name',
        ),
    ]
