# Generated by Django 4.2.7 on 2023-12-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlowerLensBackendComponent', '0011_alter_predictionresult_heatmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricstable',
            name='metrics_id',
        ),
    ]
