# Generated by Django 5.0 on 2023-12-09 11:55

import FlowerLensModel.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_id", models.CharField(max_length=100, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("version", models.CharField(max_length=100, null=True)),
                ("is_deployed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Flower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="user_uploads/")),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction", models.CharField(max_length=255)),
                ("confidence", models.CharField(max_length=255)),
                ("heatmap", models.ImageField(upload_to="heatmap_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FlowerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=FlowerLensModel.models.flower_image_directory_path
                    ),
                ),
                (
                    "flower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FlowerLensModel.flower",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatrixImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.ImageField(upload_to="matrix_images/")),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FlowerLensModel.aimodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetricsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField()),
                ("recall", models.FloatField()),
                ("f1_score", models.FloatField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FlowerLensModel.aimodel",
                    ),
                ),
            ],
        ),
    ]
