apiVersion: v1
kind: Service
metadata:
  name: flowerlens-frontend-service
spec:
  selector:
    app: flowerlens-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # If you want to expose your frontend externally
