apiVersion: v1
kind: Service
metadata:
  name: flowerlens-backend-service
spec:
  type: LoadBalancer
  selector:
    app: flowerlens-backend
  ports:
    - protocol: TCP
      port: 80  # The port the service is exposed on externally
      targetPort: 80  # The port the container is listening on
