apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DATABASE_NAME: "postgres"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "admin"
  DATABASE_HOST: "127.0.0.1"
  DATABASE_PORT: "5432"
